### ISSUE TITLE
Slickflow enterprise vs normal version

### ISSUE THREAD

**Issue by nitinjs** [besley/Slickflow#10]
what is difference between Slickflow enterprise vs normal version?

what features are supported

**Comment by besley** [comment]
The community edtion is free with the basic features, no support service. The enterprise edtion has very rich advanced features(advanced features are from workflow pattens, such as multiple instance, parallel block, intermediate event, activity firing event, timer and simulated user test) The important difference  is that we will support the customer 1year service to response their questions or fix some bugs, and also upgrade the new version for customers.
