### ISSUE TITLE
能不能提供一份mysql 的数据库脚本

### ISSUE THREAD

**Issue by tang-butian** [besley/Slickflow#16]
能不能提供一份mysql 的数据库脚本

**Comment by besley** [comment]
hi，请使用mysql workbench的数据库迁移工具从sqlserver移植就可以。

**Comment by tang-butian** [comment]
我还要专门装个sql server, 才能移植

**Comment by besley** [comment]
也可以利用实体到模型进行创建！以下是mysql的数据库建库脚本文件，请下载：
https://github.com/besley/besley.github.io/blob/master/Database/MySQL/Dump20200606.sql
