### ISSUE TITLE
WorkflowService.WithdrawProcess(WfAppRunner) 回傳error Message疑問

### ISSUE THREAD

**Issue by vincent2203** [besley/Slickflow#17]
作者您好

我在呼叫SendBackProcess以嘗試退回流程到上一步時，無法退回
我的程式碼如下
 WfAppRunner appRunner = new WfAppRunner();
 appRunner.ProcessGUID = ProcessGUID;
 appRunner.AppInstanceID = AppInstanceID;
 appRunner.AppName = AppName;
 appRunner.Version = "1";
 appRunner.UserID = "5";
 appRunner.UserName = "路天明";
 appRunner.TaskID = TaskInt;
IWorkflowService wfService = new WorkflowService();
var result = wfService.SendBackProcess(appRunner);
var msg = string.Format("流程退回结果：{0}\r\n", result.Message);

得到回傳的error訊息如下
"流程退回结果：流程退回发生异常！，详细错误：並未將物件參考設定為物件的執行個體"

請問上面寫法是哪個地方出錯?
謝謝

**Comment by besley** [comment]
请麻烦您确认一下，TaskInt的数值是当前UserID为5的用户的最新的待办任务吗？如果依然有问题，需要看到你的xml的图形，我们才能再具体排查Bug。
