### ISSUE TITLE
npmn2.0

### ISSUE THREAD

**Issue by fanhai** [besley/Slickflow#18]
是否支持 npmn2.0 标准呢？
是否支持 服务task 呢？自动执行任务，我看了一些示例好像都是 用户任务

**Comment by besley** [comment]
1) 图形元素遵循BPMN2.0，XML是XPDL语言风格，引擎高级功能，依赖自有格式来实现。
2) 流程示例中审批类型居多，所以都是用户任务，如果有服务类型Task需求，我们会在近期版本中加入的。目前Task节点本身支持绑定：组件接口、WebApi、SQL和Python脚本等，新类型的独立封装是比较方便的。

**Comment by fanhai** [comment]
非常期待下个版本能够支持 服务类型的task，最近要做一个项目，大部分都是服务类型的任务
下面是 bpmn.js 的web 界面demo ，感觉非常不错，希望slickflow 也能支持^_^
https://demo.bpmn.io/new

**Comment by besley** [comment]
好的，谢谢您的宝贵意见。服务类型的Task会支持的，流程设计器暂时还没计划去迁移到bpmn.io。但是也会考虑继续用户体验优化。

**Comment by besley** [comment]
最新版本地址：
http://demo.slickflow.com/sfd/
