### ISSUE TITLE
是否考虑 Designer 换成其他的，比如 bpmn-js

### ISSUE THREAD

**Issue by HereChen** [besley/Slickflow#2]
项目用的 BPMN 的图标只有规范 BPMN 2.0中的几个，并且生成的 XML 和 [BPMN 2.0](http://www.omg.org/spec/BPMN/2.0/) 的 example 区别比较大。

以后是否考虑换用 bpmn-js 作为设计器，对 bpmn 完美支持。

**Comment by besley** [comment]
hi，你的建议非常好，bpmn-js的确不错，我们也会考虑一下。图标的子类型是内含在里面的（下一步会增加分支和合并的子类型图标，这样会更加丰富一些，还有就是会签和加签的不同图标，一旦增加就有10来个图标了。），包括bpmn-js也是左侧标准的组件，到主界面再去选子类型。关于xml，BPMN2.0是按每一个细项作为元素节点，的确很细化，而Slickflow是以早期XPDL语言描述，以元素大类型为标识，我觉得也有可取之处。BPMN图形元素非常标准，是要采用的，而XML由于功能的实现方面，会有比较大的区别。就比如会签加签等特性的处理上。

此外，bmpn-js有个自己特有的协议，如果是MIT协议，直接采用就好；我们会和项目开发人员讨论一下。(这点限制主要是分发给客户下去的时候认为是多余的。)
http://bpmn.io/license/

**Comment by HereChen** [comment]
提出这样的问题，是因为最近看了不少开源的工作流项目，对比了一下，发现 Slickflow 技术上算是比较新一点的，同时提供了 WebApi（我最初的想法就是用 WebApi）。

突出的缺点就是 Modeler/Designer 不够完善，像 Java 的话见了好几个都是支持 BPMN2 的，比如 JBPM、Activiti，.NET 的确实没怎么见过，又特别是 Web 版的。Slickflow 还是不错的，期待进步!

**Comment by dusdong** [comment]
bmpn-js 果然很棒，希望 Slickflow 能够跟进！

**Comment by besley** [comment]
新的设计器版本已经上线，我们会一直跟进。除了增强用户体验外，也增加了弹出菜单，便于用户编辑元素节点和连线。

访问地址： http://demo.slickflow.com/sfd/#

**Comment by sunil233** [comment]
Hi can i get the English verison of the Demo and also db scripts

**Comment by besley** [comment]
database scripts:
https://github.com/besley/Slickflow/blob/master/Database/wfdb20160310.sql

There is an english demo for designer, please you can check this page.
http://demo.slickflow.com/slickflowdesigner/

**Comment by sunil233** [comment]
hi..thankyou...all the data points in the Db are in chinese version..can i have DB with Englisg version?Also any Document in english version?

**Comment by besley** [comment]
It's a pity we havent the full english version supported now. But there is a quick way to start followed some basic points for the product. 

1) The process diagram is saved in the WfProcess table with an XML schema. And an activity should be assigned with a specified ROLE(one or many).
2) The engine component will execute the completely process refrerenced by the process diagram in the step 1, there are some basic api to support the interactive, such as startup, run. All thoese activity instance data will be saved in the WfProcessInstance, WfActivityInstance, WfTransitionInstance and WfTasks tables.
3) there is an web api demo in the Slickflow.WebApi project, it is convinennt to test with RESTClient toolkit installed in Firefox(it is only one of web api test toolkit for programmers). 
4) It's better to begin with a sequence process, then you can have a split/join style process.

We also provide technical service for Enterprise version customers, if you have any further query, please feel free to contact us. Thanks.

**Comment by besley** [comment]
新版设计器已经使用mxGraph框架用来编辑流程图形。在线体验地址：
 http://demo.slickflow.com/sfd/
