### ISSUE TITLE
How to invoke a custom class function on step competed

### ISSUE THREAD

**Issue by papyr** [besley/Slickflow#20]
Hello during a step how to attach the workflow so it can invoke a function with an argument from the slickflow process.

For e.g. on slickflow `PurchaseRequest.Recieved(`Call my custom `ManagerClass.RequestApproval(User, document, amount`))

thanks

**Comment by besley** [comment]
You can define some actions when an activity completed. At present, the engine support LocalService, C# component, SQL, Store Procedure, WebAPI and Python Script.

![activity-property-action](https://user-images.githubusercontent.com/2442853/90996375-2fcc0400-e5f1-11ea-8f8f-27ec59a994b4.png)

It's a pity that the feature is not useable in the Community Edition, it can be used in the Enterprise Edtion.

**Comment by besley** [comment]
![activity-property-action](https://user-images.githubusercontent.com/2442853/90996346-15922600-e5f1-11ea-9eb6-0eec356b04b4.png)

**Comment by papyr** [comment]
great thanks 💯
