### ISSUE TITLE
List all processes and current status like a Mail Inbox

### ISSUE THREAD

**Issue by papyr** [besley/Slickflow#21]
Hello, it would be nice to see a list of current pending status of the workflows as a list.

For e.g. when a User logs in he wants to know in ASP MVC GUI, what all items have been assigned to him and the current status, 

Basically a GUI to watch all process and current status / steps as an Inbox in ASP MVC/Core [like this ](https://bit.ly/3gbV0mV) , 
Link to [Code sample for inbox workflows](https://bit.ly/3iYorKZ)

![image](https://user-images.githubusercontent.com/12733414/90828355-dcfdfe00-e30b-11ea-9425-b867cbdaff5a.png)

**Comment by besley** [comment]
There is a table named WfTasks in the database, you can retrieve the current user tasks from this table. In the IWorkflowService file, there is a method of GetReadyTasks() to do this requirement.

**Comment by papyr** [comment]
thanks, I see you have query argument, can you share a snippet on how to query for _current user, active and overdue tasks._
