### ISSUE TITLE
MVC demo error

### ISSUE THREAD

**Issue by papyr** [besley/Slickflow#22]
Hello, the flow chart is not showing also the master detail on the main grid for each process does not pull up the data. I was trying to implement this very scenario.

One suggestion, can we do the latest BootStrap 4

![image](https://user-images.githubusercontent.com/12733414/91496741-a8012680-e88a-11ea-99ba-b019fdb4aae0.png)

**Comment by besley** [comment]
Hi, We have fixed this issue, please check it again. Thanks!
![image](https://user-images.githubusercontent.com/2442853/91634261-9b630680-ea21-11ea-895e-4d0d9aed5ae4.png)

**Comment by besley** [comment]
Ok, The Bootstrap 4 is a choice, thanks for your suggestion we will upgrade it in next stage.

**Comment by papyr** [comment]
just checking if BS 4 was updated also .NET 5 and .NET 6 was released last week

**Comment by besley** [comment]
Hi, after we reviewed the BS4, there isn't a perfect dialog component. We have to recommend the customers to think about the Quasar framework based on the Vue. At the present, the engine project has been upgraded to the .net core3.1.

**Comment by papyr** [comment]
Hey  can I mix and match ASP core with Quasar, I am very new to that.

Is there a sample you could list, or with RxJS 

Also check this [out](https://dwkit.com/demo/) its on [GitHub ](https://github.com/optimajet/WorkflowEngine.NET)

**Comment by besley** [comment]
Please you can access this middleware project, it's very helpful to integrate with Quasar framework and Asp.NET Core.

VueCliMiddleware:
https://github.com/EEParker/aspnetcore-vueclimiddleware

**Comment by besley** [comment]
Please you can access this middleware project, it's very helpful to integrate with Quasar framework and Asp.NET Core.

VueCliMiddleware:
https://github.com/EEParker/aspnetcore-vueclimiddleware

**Comment by besley** [comment]
Hi, there is a Quasar Form Builder open source project, it seems very nice. :-)
https://github.com/baggachipz/q-form-builder

**Comment by besley** [comment]
@papyr, we have submitted a new form designer product: SlickQua, it's based on Quasar framework. Compared with q-form-build project, SlickQua is more suitable for users:

1) based on vue-gridlayout framework to drag and drop;
2) can be integrated with Slickflow.Net engine;
3) database persistence can be used to save form template and form inputing data;
4) provided datasource binding and cascading features for dropdown, list, checkbox and radio control;
5) provided event binding feature for onchange/onclick event;
6) implemented activity/field permission feature to show/hide, write/readonly form inputing controls

http://demo.slickflow.com/sqd/

[SlickQua AskforLeave Demo](https://github.com/besley/besley.github.io/blob/master/Gif/SlickQua-Ask4Leave-Demo.gif)

**Comment by papyr** [comment]
BTW - check out workflowengine on github its also a .net C#
