### ISSUE TITLE
WorkflowService.cs中GetFirstActivityRoleUserTree有一处请指教

### ISSUE THREAD

**Issue by Cwsper** [besley/Slickflow#23]
1.7.6
Slickflow/NETCORE/Slickflow/Source/Slickflow.Engine/Service/WorkflowService.cs
383行

        /// <summary>
        /// 流程启动时获取开始节点下一步的节点角色人员列表
        /// 统一整合到: GetNextActivityRoleUserTree()
        /// </summary>
        /// <param name="runner">应用执行人</param>
        /// <param name="condition">条件</param>
        /// <returns>节点列表</returns>
        public IList<NodeView> GetFirstActivityRoleUserTree(WfAppRunner runner, 
            IDictionary<string, string> condition = null)
        {
            var processModel = ProcessModelFactory.Create(runner.ProcessGUID, runner.Version);
            var firstActivity = processModel.GetFirstActivity();
            var nextSteps = processModel.GetNextActivityTree(firstActivity.ActivityGUID,
                condition);

            foreach (var ns in nextSteps)
            {
                var roleIDs = ns.Roles.Select(x => x.ID).ToArray();
                ns.Users = ResourceService.GetUserListByRoleReceiverType(roleIDs, runner.UserID, (int)ns.ReceiverType);     //增加转移前置过滤条件
            }
            return nextSteps;
        }

383行的 var firstActivity = processModel.GetFirstActivity();是否应该是processModel.GetStartActivity()？

现行代码中，383行取First，384行再取Next，实际效果就是取到了Start后的第二个。而本方法的本意是“流程启动时获取开始节点下一步的节点角色人员列表”

请问这个确实是个bug，还是我理解和测试方法错误。

谢谢。

**Comment by besley** [comment]
是为了当前第一个办理节点完成时，弹窗进行第二步的用户角色选择。比如填写请假单，通常流程触发是填写请假表单完成后，转给部门领导审批才算流程实例开启，此处也可以根据自己的需要来处理。

**Comment by Cwsper** [comment]
感谢大佬回复

明白你说的意思了，你描述的场景确实是事实，取的确实是Start+2的节点信息。

我根据自己场景修改吧

再次感谢回复
