### ISSUE TITLE
error saving process

### ISSUE THREAD

**Issue by papyr** [besley/Slickflow#25]
Hi, I really like the idea of Process Templates, its a time saver, but I am still getting errors. I was able to update and run some of it in .NET 5.03 (much faster!!!) but I got some errors

This could be a nice enterprise tool, if it was polished a little more on the UI, and developer ease of use to quickly customize.

I work with people who are Power Users and would love something like this if they thought it could replace the designer something like Optim Workflow Engine .net here on github. I was trying to show them the templates and they loved the idea, but had some questions around this.

![image](https://user-images.githubusercontent.com/12733414/110813801-d78be500-8256-11eb-8336-0da1a6dbc916.png)

**Comment by besley** [comment]
Hi, there is a language localization missing error in the Slickflow.Graph project, we will fix this bug later.

The error message showed that there is a process record with the same process code and version property, so you can change the new version field(such as 2, if the original version number is 1)  to make the record be an unique one.

**Comment by besley** [comment]
Hi, there is a language localization missing error in the Slickflow.Graph project, we will fix this bug later.

The error message showed that there is a process record with the same process code and version property, so you can change the new version field(such as 2, if the original version number is 1)  to make the record be an unique one.

**Comment by besley** [comment]
Yes, the process template can really save time especially when the process administrator or manager has to design the similar process every time.

By the way, there is an article to describe process template skills if you have interesting to be familiarized with it. 

https://www.codeproject.com/Articles/5252483/Slickflow-Coding-Graphic-Model-User-Manual

**Comment by besley** [comment]
The bug has been fixed when there is a duplicated process file record, please you can try on it on designer page. Thanks
