### ISSUE TITLE
/Scripts/localhelper.js 404 Not Found

### ISSUE THREAD

**Issue by cluyun** [besley/Slickflow#26]
/Scripts/localhelper.js 404 Not Found

**Comment by besley** [comment]
Can you tell me which project miss this file ? There is also another position here:
https://github.com/besley/Slickflow/blob/master/NET/Slickflow/Source/Slickflow.Designer/Scripts/localhelper.js

**Comment by cluyun** [comment]
> Can you tell me which project miss this file ? There is also another position here:
> https://github.com/besley/Slickflow/blob/master/NET/Slickflow/Source/Slickflow.Designer/Scripts/localhelper.js

The mistake is pointing here
https://github.com/besley/Slickflow/tree/master/NET/Slickflow/Source/Slickflow.Designer/Scripts

**Comment by besley** [comment]
The new net6 version project has been updated. you can download it now.
