### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by hwgeone** [besley/Slickflow#3]
**严重性	代码	说明	项目	文件	行	禁止显示状态
错误		指定的任务可执行文件位置“C:\Users\wei.huang\Desktop\ESO\流程引擎\Slickflow-master\Slickflow-master\SlickflowCE\Slickflow\Source\packages\Microsoft.Net.Compilers.1.0.0\build\..\tools\csc.exe”无效。	Slickflow.Designer**			

我编译此项目，只出现这一个错文，我用的2017vs社区版打开的，管理员运行的。请问这个错误是因为什么？我该怎么解决？ 
希望得到答复，谢谢！

**Comment by besley** [comment]
Github无法直接上传exe可执行文件，所以请单独下载Binary的文件包，然后复制到相应目录就可以。
