### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Diaskhan** [besley/Slickflow#6]
Could U provide Infromation how run and install slickflow demo  ?

**Comment by besley** [comment]
If you get the community version from github, you can make this step:
1. there is a database sql script file in netcore database directory, you need run this sql;;
2. the project slickflow.orderdemo is a order process from order generated and product deliveried lifecycle, and it's better to setup an IIS virtual application to run this demo;
3. modify the database connection string to match your local server enviorment;

Also, there is an online demo in slickflow website:
http://demo.slickflow.com/sfd/

After you create a simple process through the desiger, there is an option->[simulation test] feature to make the process to start until complete. Mostly this feautre is for programmers to do some tesing.

Quick Start Document on the Code Project:
https://www.codeproject.com/Articles/5246528/Slickflow-NET-Core-Open-Source-Workflow-Engine
