### ISSUE TITLE
can run the project

### ISSUE THREAD

**Issue by hijudy** [besley/Slickflow#7]
1. the file engining->service->WorkflowService.cs里面都是语法错误，不能编译通过。
2. design项目，我是vs2013，我看这个项目用的是Microsoft.Net.Compilers.2.10.0版本，编译的时候报错。其实package里面有这个版本。
错误信息：错误	29	未能从程序集 D:\_Develop\工作流\Slickflow\NET\Slickflow\Source\packages\Microsoft.Net.Compilers.2.10.0\build\..\tools\Microsoft.Build.Tasks.CodeAnalysis.dll 加载任务“Microsoft.CodeAnalysis.BuildTasks.Csc”。未能加载文件或程序集“Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。 请确认 <UsingTask> 声明正确，该程序集及其所有依赖项都可用，并且该任务包含实现 Microsoft.Build.Framework.ITask 的公共类。	Slickflow.Designer

**Comment by besley** [comment]
建议.net framework4.5, vs2017以上版本配置环境。其它NuGet更新相应组件。
