### ISSUE TITLE
关于流程的设计

### ISSUE THREAD

**Issue by hijudy** [besley/Slickflow#8]
我看了一下demo，有几个问题：
1. 设计器里面任务节点只能配置角色，可以给节点设置选择人员吗？
2. demo里面是每走一步选择下一步的审核人员。用户是否可以在发起流程时，把每个节点的人都同时选好吗？这样后面节点的审核者只需要通过或者驳回就可以，不需要再选择下一个节点的人员。在图纸设计审核的时候，实际上是设计员自己去给相关领导去签字，领导并不关心他签完字后，下面是谁签字。

**Comment by besley** [comment]
1. 流程定义是支持人员定义的，只是需要客户自己去对接人员表，默认角色的好处就是人员变动时候，不用再去修改流程定义（比如人员会转部门或者离职等）；
2. 可以流转时候，判断是否需要弹窗人员选择框确认，这个步骤可以让程序自动来完成，比如匹配到下一步的办理用户列表，就群发任务（尤其是单个办理人员就不用再去弹框选择），接口里面这样的方法，在集成的时候封装一下就可以的。
