### ISSUE TITLE
configuring tasks and their sequence through xml

### ISSUE THREAD

**Issue by nitinjs** [besley/Slickflow#9]
hi besley,

is it possible to configure tasks and their sequence through xml?

-nitin

**Comment by besley** [comment]
Hi, nitinjs, 
The designer will generate xml content when the user draw a diagram. You can review the xml format through desiger page tool menu(http://demo.slickfow.com/sfd). This xml is stored into the database, so the next time, when open a diagram, it also load the xml from database, and deserialzie it into a diagram on canvas, included to get the property of activity or transition. Is it convenient to convert your xml to slickflow format, or using some xslt way?
